name: Generate Post Files

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install aiogram requests Pillow

      - name: Run Generator
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py

      - name: Upload Post Files
        uses: actions/upload-artifact@v4
        with:
          name: news-post-files
          path: |
            post_image.jpg
            post_caption.txt
